/* 
 * Category Action Types
 */

export const SELECT_CATEGORY    = "SELECT_CATEGORY";
export const CATEGORIES_REQUEST = "CATEGORIES_REQUEST";

// GET
export const GET_CATEGORIES_SUCCESS = "GET_CATEGORIES_SUCCESS";
export const GET_CATEGORIES_FAILURE = "GET_CATEGORIES_FAILURE";

// POST
export const POST_CATEGORY_SUCCESS = "POST_CATEGORY_SUCCESS";
export const POST_CATEGORY_FAILURE = "POST_CATEGORY_FAILURE";

// PUT
export const PUT_CATEGORY_SUCCESS = "PUT_CATEGORY_SUCCESS";
export const PUT_CATEGORY_FAILURE = "PUT_CATEGORY_FAILURE";

export const PUT_CATEGORIES_SUCCESS = "PUT_CATEGORIES_SUCCESS";
export const PUT_CATEGORIES_FAILURE = "PUT_CATEGORIES_FAILURE";

// DELETE
export const DELETE_CATEGORY_SUCCESS = "DELETE_CATEGORY_SUCCESS";
export const DELETE_CATEGORY_FAILURE = "DELETE_CATEGORY_FAILURE";

